### ISSUE TITLE
Outdated Dependencies

### ISSUE THREAD

**Issue by GDHub** [impactmass/symmetrical-octo-garbanzo#11] opened 2017-02-27 10:14 UTC
the bluebird and joi dependencies are outdated and npm warns of DOS attack on one of the dependencies.

**Comment by impactmass** [comment] 2017-04-13 12:13
@GDHub Okay. Thanks for reporting this. I'll check this ASAP

**Comment by impactmass** [comment] 2017-04-13 16:36
Hi @GDHub, I just did a fresh install of this package into a test Cordova project right now... and there was no warning about outdated dependencies nor DOS attack. 

Here's a dump of my log:

```
$ npm install cordova-rave
/Users/seunmartins/source/hello
└─┬ cordova-rave@1.1.0
  ├── bluebird@3.5.0
  ├── core-js@2.4.1
  ├─┬ joi@10.4.1
  │ ├── hoek@4.1.1
  │ ├── isemail@2.2.1
  │ ├── items@2.1.1
  │ └── topo@2.0.2
  ├── joi-browser@10.0.6
  ├── lodash@4.17.4
  ├─┬ node-fetch@1.6.3
  │ ├─┬ encoding@0.1.12
  │ │ └── iconv-lite@0.4.15
  │ └── is-stream@1.1.0
  ├─┬ npmlog@4.0.2
  │ ├─┬ are-we-there-yet@1.1.2
  │ │ ├── delegates@1.0.0
  │ │ └─┬ readable-stream@2.2.9
  │ │   ├── buffer-shims@1.0.0
  │ │   ├── core-util-is@1.0.2
  │ │   ├── inherits@2.0.3
  │ │   ├── isarray@1.0.0
  │ │   ├── process-nextick-args@1.0.7
  │ │   ├── string_decoder@1.0.0
  │ │   └── util-deprecate@1.0.2
  │ ├── console-control-strings@1.1.0
  │ ├─┬ gauge@2.7.3
  │ │ ├── aproba@1.1.1
  │ │ ├── has-unicode@2.0.1
  │ │ ├── object-assign@4.1.1
  │ │ ├── signal-exit@3.0.2
  │ │ ├─┬ string-width@1.0.2
  │ │ │ ├── code-point-at@1.1.0
  │ │ │ └─┬ is-fullwidth-code-point@1.0.0
  │ │ │   └── number-is-nan@1.0.1
  │ │ ├─┬ strip-ansi@3.0.1
  │ │ │ └── ansi-regex@2.1.1
  │ │ └── wide-align@1.1.0
  │ └── set-blocking@2.0.0
  └─┬ prompt@1.0.0
    ├── colors@1.1.2
    ├── pkginfo@0.4.0
    ├─┬ read@1.0.7
    │ └── mute-stream@0.0.7
    ├── revalidator@0.1.8
    ├─┬ utile@0.3.0
    │ ├── async@0.9.2
    │ ├── deep-equal@0.2.2
    │ ├── i@0.3.5
    │ ├─┬ mkdirp@0.5.1
    │ │ └── minimist@0.0.8
    │ ├── ncp@1.0.1
    │ └─┬ rimraf@2.6.1
    │   └─┬ glob@7.1.1
    │     ├── fs.realpath@1.0.0
    │     ├─┬ inflight@1.0.6
    │     │ └── wrappy@1.0.2
    │     ├─┬ minimatch@3.0.3
    │     │ └─┬ brace-expansion@1.1.7
    │     │   ├── balanced-match@0.4.2
    │     │   └── concat-map@0.0.1
    │     ├── once@1.4.0
    │     └── path-is-absolute@1.0.1
    └─┬ winston@2.1.1
      ├── async@1.0.0
      ├── colors@1.0.3
      ├── cycle@1.0.3
      ├── eyes@0.1.8
      ├── isstream@0.1.2
      ├── pkginfo@0.3.1
      └── stack-trace@0.0.9

npm WARN enoent ENOENT: no such file or directory, open './source/hello/package.json'
npm WARN hello No description
npm WARN hello No repository field.
npm WARN hello No README data
npm WARN hello No license field.

```
As you can see, there's no warning about outdated dependencies/DOS. 

Here is my suggestion on things you can check:
* Confirm that you don't have other packages getting installed. They warnings you talk about might be coming from other packages you're using.

**Comment by impactmass** [comment] 2017-04-13 16:37
I'll close this out, but if you think there's still an issue to look into, please feel free to re-open

**Closed as completed by impactmass** 2017-04-13 16:37 UTC

**Comment by impactmass** [comment] 2017-04-13 17:17
After checking again, I found what you're referring to. It's caused by `gulp`. The current version of gulp still uses minimatch@2.0.10, which is what is causing the warning:

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

This is also logged on gulp's codebase [here](https://github.com/gulpjs/gulp/issues/1719).  The thing to be aware of from the discussion there is that, this package is fine as long as we validate the input being passed in (and that's why we have joi in there).

That said, I'll keep watch on gulp's next release (if they update the minimatch).

**Comment by sirKings** [comment] 2017-06-23 14:57
Hello, have tried to use the ravepay on an ionic2 app, followed the steps as instructed but for some reason 'initRavePay' is not a function is the error i am getting. Was this not designed for Ionic2

**Comment by impactmass** [comment] 2017-06-23 16:34
Hi @sirKings.

Yes, it should work with Ionic 2, since it's also powered by/with Cordova. But the way you set it up will be the determining factor. If you can give a sample setup of what you have, that can be helpful in helping with troubleshooting.

**Comment by sirKings** [comment] 2017-06-23 16:48
Most plugins I am using, I install using the command line, add the plugin to my app.module.ts, import it in the ts file of the page i want to use it in, and finally create an instance of it in the constructor of the page. that way the methods in that plugin is made available in the page class. So its more like thats where my problem is coming from. If there is a way to create an local instance of the plugin in the page, that could solve the problem
