### ISSUE TITLE
Validation page opens in browser

### ISSUE THREAD

**Issue by poliha** [impactmass/symmetrical-octo-garbanzo#19] opened 2017-08-09 15:42 UTC
The page to enter otp after entering your card details opens in a browser. 
The response is then not passed to receive callback and hence can't process it in my app.

**Comment by impactmass** [comment] 2017-08-10 13:40
Testing to reproduce.

**Comment by impactmass** [comment] 2017-08-10 21:55
I made a test payment just now with the Rave Live. Every step about the transaction happened within the Rave modal, it doesn't go into the browser. 

Can you give me more details about your case, so I can reproduce this properly?

**Comment by poliha** [comment] 2017-08-10 22:01
This occurs when using cards that require 3DSecure processing like intl visa and mastercards. 
Also using test rave account shows this behaviour.

**Comment by poliha** [comment] 2017-08-23 21:12
@impactmass Any luck with this?

**Comment by impactmass** [comment] 2017-08-28 10:32
No, not yet. I'll post a more detailed update later today.

**Comment by Oaseru17** [comment] 2017-12-10 15:59
still waiting on this.. cant processed with payment for international card.. cause of thus error..

**Comment by impactmass** [comment] 2017-12-11 09:13
Hi @precious171 , apologies for no reply on this for a long time. This is caused by my other duties. 
- Do you have any hints about why it opens up in a new page?
- I will be digging into some of these issues in some days, but if that is too late for you, you can post what you're find here, and we can chat along. It's possible you might be able to solve it before I'm back.

**Comment by Oaseru17** [comment] 2017-12-11 11:01
i think its no fault of urz the .. api flow requires opening a url for validation.. except your using the inapp browser.. this has to occur as all web payment require, but app do not.. like in your android version .. Please can you rebuild the plugin using the android flow.. i could help build it as i need it ASAP but i need to bypass the requirement for OTP/PIN or secure code as all mobile payment do..  Also you can use braintree's process flow or even paystack's flow.. I tried creating the plugin last night using the rest api but got stuck as your api all requires this OTP/PIN or secure code which should not be for mobile payment

https://developers.braintreepayments.com/start/overview

**Comment by teebazz** [comment] 2018-01-04 14:39
Happy New year guys. 
Hope we all had a splendid holiday.

Please any way forward on these issue

**Comment by impactmass** [comment] 2018-01-05 12:43
- @precious171, you metioned this is something you can fix, but you need to bypass the OTP/PIN requirement? I'm not sure how that can be accomplished, as the OTP/PIN requirement is set by Rave itself and not this wrapper lib. Maybe contact them about it?
- @precious171 to your thought about using another flow other than the web flow. That's a good idea, but this wrapper was built with Cordova in mind (and as far as I know, that depends on web technologies HTML, CSS, JS). Please explain more if that's not the case.

**Comment by impactmass** [comment] 2018-01-05 12:46
@teebazz potential way forward might be what @precious171 is suggesting, or confirming what the result of the verification that is done in the new window is... then see if the Rave modal can respond after it's close.

**Comment by Oaseru17** [comment] 2018-01-05 12:47
i was with the impression that you work for rave.. i used the web verification and listened to the web url change.. risky but the only option i had

**Comment by Oaseru17** [comment] 2018-01-05 12:50
processaction1(rowid,emailaddress){
    const ref = this.iab.create('http://--urllink/?servertxt=ZEXPOO'+rowid+'&email='+emailaddress+'&description='+this.actiontype+'%20Purchase&title=Zend Exchange&amount='+this.truecost+'%2E00', '_blank', 'location=yes,toolbar=no,enableviewportscale=yes');
    ref.on("exit").subscribe((event) =>  {
                    console.log("event exit");
                        console.log(event);
                             ref.close();
                   });

ref.on("loadstart").subscribe((event) => {
                               console.log("event start");
                               if(event.url.indexOf("blacklist") !== -1){
console.log("black list found");
   ref.close();
var str = decodeURIComponent(event.url);
 // prints substring from index 3
    console.log(str);
var returnData  = str.substring(55);



                          var returnObj = JSON.parse(returnData);

                          if(returnObj.status = "successful" ){


                            if(this.actiontypevalue == 0){
                        this.finalizepayment(returnObj.flwRef,this.pointvalue,this.actiontypevalue,rowid);
                            }else{
                      this.finalizepayment(returnObj.flwRef,this.subvalue,this.actiontypevalue,rowid);





                            }


                          }else{
                            let alert = this.alertCtrl.create({
                          title: 'PE406 : Payment error',
                          subTitle: 'Please try again or contact zend',
                          buttons: ['Dismiss']
                        });
                        alert.present();
                          }

                               }
                                   console.log(event);
                             });


  }

**Comment by Oaseru17** [comment] 2018-01-05 12:54
@impactmass what i meant by passing the OTP/PIN was i tested the android core library for rave. and they didnt require OTP/PIN .. same in iOS.. i tried creating a new ionic plugin based on that .. due to the fact i could get the rest api url they used from the android plugin ... its taking a while.. i will create a new one once i launch my app and have time to do so

**Comment by Oaseru17** [comment] 2018-01-05 13:27
@impactmass please can u send me the list of urls u used i want to cross check against my i found in the android plugin.. (preciousoaseru993@gmail.com)

**Comment by teebazz** [comment] 2018-01-08 09:40
sup pple. 
Please whats d update on this issue??

**Comment by teebazz** [comment] 2018-01-15 08:44
Hello @impactmass and @precious171.

Hw re you sirs??

Please whats up and updates on d plugins.
Hope to hear from you soon

**Comment by impactmass** [comment] 2018-01-15 13:03
Hi @teebazz,  bandwidth constraints have not let me come around to this issue. 

At this point, I can only refer you back to my last response to you.

> @teebazz potential way forward might be what @precious171 is suggesting, or confirming what the result of the verification that is done in the new window is... then see if the Rave modal can respond after it's close.

Maybe this can be lead up to a contribution.

**Comment by impactmass** [comment] 2018-01-23 00:16
After looking into this new window problem, I find that:
- Correctly getting back to the app context after moving to the browser is fickle
- The current approach of using the web tech layer of Cordova (mostly HTML/JS) doesn't cover all the mobile nuances (e.g what we're seeing on this issue)

To solve this problem:
- Rewrite the plugin to leverage actual Cordova native resources (iOS - ObjC/Swift, Android - Java) thus properly handling 
- This is a relatively big rewrite and will span a couple of weeks.
- I'll be creating issues on the repo detailing the approach and progress. Any one who wants to contribute or follow along can comment on the issues as they get created.

**Comment by poliha** [comment] 2018-01-23 13:52
@impactmass it might be worth looking at the [Paypal Ionic plugin](https://ionicframework.com/docs/native/paypal/), Their repo might give you some ideas.

**Comment by temiadesina** [comment] 2018-10-29 20:02
Hi Guys, just an update the Cordova SDK now loads in an in-app Cordova browser.

We are also launching a new Ionic 3 Plugin to deal specifically for Ionic.

Please check out the new releases made to the SDK.

**Comment by impactmass** [comment] 2018-11-08 10:04
Fixed in #36, shipped in [v1.3.0](https://github.com/impactmass/cordova-rave/releases/tag/v1.3.0); npm [🔗](https://www.npmjs.com/package/cordova-rave/v/1.3.0). Thanks @temiadesina 	and everyone

**Closed as completed by impactmass** 2018-11-08 10:04 UTC
Labels: bug
