### ISSUE TITLE
VISA PAYMENT VERIFICATION ISSUE 

### ISSUE THREAD

**Issue by teebazz** [impactmass/symmetrical-octo-garbanzo#23] opened 2017-12-22 17:40 UTC
Please the visa verification opens in the external browser and after dat is done . the rave response is just dumped in the browser and doesnt got back to the app.

Please Help

**Comment by impactmass** [comment] 2017-12-22 23:05
Possible a duplicate of #19 which is still an open issue.

**Closed as completed** 2018-01-04 14:38 UTC
